apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  annotations:
    helmcharts.cattle.io/managed-by: helm-controller
  finalizers:
    - wrangler.cattle.io/on-helm-chart-remove
  name: longhorn
  namespace: default
spec:
  repo: https://charts.longhorn.io
  chart: longhorn
  version: 1.8.0
  targetNamespace: longhorn-system
  failurePolicy: abort
  createNamespace: true
  valuesContent: |
    # -- Annotation for the Longhorn Manager DaemonSet pods. This setting is optional.
    annotations:
       # Actually this needs to be applied to the instance manager and not the longhorn-manager...
       # Limit Networkspeeds so that replication and backups don't kill the network
       # See also https://github.com/longhorn/longhorn/issues/5692
       kubernetes.io/ingress-bandwidth: 500M
       kubernetes.io/egress-bandwidth: 250M
    
    defaultBackupStore:
      # -- Endpoint used to access the default backupstore.
      backupTarget: s3://longhorn@s3.nue.felix-prasse.de/default/
      # -- Name of the Kubernetes secret associated with the default backup target.
      backupTargetCredentialSecret: "s3-nue-secret"
      # -- Number of seconds that Longhorn waits before checking the default backupstore for new backups.
      pollInterval: 300


---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: longhorn-ingress
  namespace: longhorn-system
  annotations: {}
    # TODO
    # type of authentication
    #nginx.ingress.kubernetes.io/auth-type: basic
    # prevent the controller from redirecting (308) to HTTPS
    #nginx.ingress.kubernetes.io/ssl-redirect: 'false'
    # name of the secret that contains the user/password definitions
    #nginx.ingress.kubernetes.io/auth-secret: basic-auth
    # message to display with an appropriate context why the authentication is required
    #nginx.ingress.kubernetes.io/auth-realm: 'Authentication Required '
    # custom max body size for file uploading like backing image uploading
    #nginx.ingress.kubernetes.io/proxy-body-size: 10000m
spec:
  ingressClassName: internal-nginx
  rules:
    - host: longhorn.home.arpa
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: longhorn-frontend
                port:
                  number: 80

---
apiVersion: v1
kind: Secret
metadata:
  name: longhorn-crypto
  namespace: longhorn-system
stringData:
  CRYPTO_KEY_VALUE: "{{crypto_key}}"
  CRYPTO_KEY_PROVIDER: "secret"
  CRYPTO_KEY_CIPHER: "aes-xts-plain64"
  CRYPTO_KEY_HASH: "sha256"
  CRYPTO_KEY_SIZE: "256"
  CRYPTO_PBKDF: "argon2i"
---
apiVersion: v1
data:
  AWS_ACCESS_KEY_ID: "{{AWS_ACCESS_KEY_ID}}"
  AWS_SECRET_ACCESS_KEY: "{{AWS_SECRET_ACCESS_KEY}}"
  AWS_ENDPOINTS: "{{AWS_ENDPOINTS}}"
kind: Secret
metadata:
  name: s3-nue-secret
  namespace: longhorn-system
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: longhorn-boot
provisioner: driver.longhorn.io
allowVolumeExpansion: true
reclaimPolicy: Retain
mountOptions:
  - discard
parameters:
  numberOfReplicas: "3"
  staleReplicaTimeout: "2880" # 48 hours in minutes
  fromBackup: ""
  fsType: "ext4"
#  backupTargetName: "default"
#  mkfsParams: "-I 256 -b 4096 -O ^metadata_csum,^64bit"
  diskSelector: "boot"
  encrypted: "true"
  # global secret that contains the encryption key that will be used for all volumes
  csi.storage.k8s.io/provisioner-secret-name: "longhorn-crypto"
  csi.storage.k8s.io/provisioner-secret-namespace: "longhorn-system"
  csi.storage.k8s.io/node-publish-secret-name: "longhorn-crypto"
  csi.storage.k8s.io/node-publish-secret-namespace: "longhorn-system"
  csi.storage.k8s.io/node-stage-secret-name: "longhorn-crypto"
  csi.storage.k8s.io/node-stage-secret-namespace: "longhorn-system"
  csi.storage.k8s.io/node-expand-secret-name: "longhorn-crypto"
  csi.storage.k8s.io/node-expand-secret-namespace: "longhorn-system"
---
# Storage class for Application level replication (Databases, Minio, ...)
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: longhorn-boot-no-replication
provisioner: driver.longhorn.io
allowVolumeExpansion: true
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
mountOptions:
  - discard
parameters:
  numberOfReplicas: "1"
  staleReplicaTimeout: "2880" # 48 hours in minutes
  fromBackup: ""
  fsType: "ext4"
  #  backupTargetName: "default"
  #  mkfsParams: "-I 256 -b 4096 -O ^metadata_csum,^64bit"
  diskSelector: "boot"
  encrypted: "true"
  # global secret that contains the encryption key that will be used for all volumes
  csi.storage.k8s.io/provisioner-secret-name: "longhorn-crypto"
  csi.storage.k8s.io/provisioner-secret-namespace: "longhorn-system"
  csi.storage.k8s.io/node-publish-secret-name: "longhorn-crypto"
  csi.storage.k8s.io/node-publish-secret-namespace: "longhorn-system"
  csi.storage.k8s.io/node-stage-secret-name: "longhorn-crypto"
  csi.storage.k8s.io/node-stage-secret-namespace: "longhorn-system"
  csi.storage.k8s.io/node-expand-secret-name: "longhorn-crypto"
  csi.storage.k8s.io/node-expand-secret-namespace: "longhorn-system"

---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: longhorn-ssd
provisioner: driver.longhorn.io
allowVolumeExpansion: true
reclaimPolicy: Retain
mountOptions:
  - discard
parameters:
  # TODO This doesn't work for large replicas...
  # See https://github.com/longhorn/longhorn/issues/9626
  # Even with very limited bandwidth the fujitsu s920 nodes run into high cpu problems resulting in connection resets.
  numberOfReplicas: "3"
  staleReplicaTimeout: "2880" # 48 hours in minutes
  fromBackup: ""
  fsType: "ext4"
  #  backupTargetName: "default"
  #  mkfsParams: "-I 256 -b 4096 -O ^metadata_csum,^64bit"
  diskSelector: "ssd"
  encrypted: "true"
  # global secret that contains the encryption key that will be used for all volumes
  csi.storage.k8s.io/provisioner-secret-name: "longhorn-crypto"
  csi.storage.k8s.io/provisioner-secret-namespace: "longhorn-system"
  csi.storage.k8s.io/node-publish-secret-name: "longhorn-crypto"
  csi.storage.k8s.io/node-publish-secret-namespace: "longhorn-system"
  csi.storage.k8s.io/node-stage-secret-name: "longhorn-crypto"
  csi.storage.k8s.io/node-stage-secret-namespace: "longhorn-system"
  csi.storage.k8s.io/node-expand-secret-name: "longhorn-crypto"
  csi.storage.k8s.io/node-expand-secret-namespace: "longhorn-system"