apiVersion: v1
kind: Namespace
metadata:
  name: ingress-nginx
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: ingress-internal
  namespace: kube-system
spec:
  repo: https://kubernetes.github.io/ingress-nginx
  chart: ingress-nginx
  version: 4.12.1
  targetNamespace: ingress-nginx
  valuesContent: |-
    controller:
      # Must be the same as for kube vip due to externalTrafficPolicy: Local
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/master
                operator: Exists
            - matchExpressions:
              - key: node-role.kubernetes.io/control-plane
                operator: Exists
      electionID: internal-ingress-controller-leader
      ingressClass: internal-nginx  # default: nginx
      ingressClassResource:
        name: internal-nginx  # default: nginx
        enabled: true
        default: false
        controllerValue: "k8s.io/internal-ingress-nginx"  # default: k8s.io/ingress-nginx
      service:
        # Set to local to preserve the source ip and reduce the amount of hops (kube-vip should use the leader election to only advertise the nodes that have a pod running)
        externalTrafficPolicy: Local
        annotations: 
         kube-vip.io/loadbalancerIPs: 192.168.2.91
---
# TODO https://kubernetes.github.io/ingress-nginx/user-guide/third-party-addons/modsecurity/
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: ingress-public
  namespace: kube-system
spec:
  repo: https://kubernetes.github.io/ingress-nginx
  chart: ingress-nginx
  version: 4.12.1
  targetNamespace: ingress-nginx
  valuesContent: |-
    controller:
      # Must be the same as for kube vip due to externalTrafficPolicy: Local
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/master
                operator: Exists
            - matchExpressions:
              - key: node-role.kubernetes.io/control-plane
                operator: Exists
      electionID: public-ingress-controller-leader
      ingressClass: public-nginx  # default: nginx
      ingressClassResource:
        name: public-nginx  # default: nginx
        enabled: true
        default: false
        controllerValue: "k8s.io/public-ingress-nginx"  # default: k8s.io/ingress-nginx
      service:
        # Set to local to preserve the source ip and reduce the amount of hops (kube-vip should use the leader election to only advertise the nodes that have a pod running)
        externalTrafficPolicy: Local
        annotations: 
         kube-vip.io/loadbalancerIPs: 192.168.2.93
---