apiVersion: v1
kind: Namespace
metadata:
  name: pihole
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: pihole
  namespace: pihole
spec:
  repo: https://mojo2600.github.io/pihole-kubernetes/
  chart: pihole
  targetNamespace: pihole
  valuesContent: |-
    virtualHost: pihole.home.arpa
    dnsmasq:
      customDnsEntries:
        - address=/demo/192.168.2.103
    
    persistentVolumeClaim:
      enabled: false
    
    serviceWeb:
      type: LoadBalancer
      loadBalancerIP: 192.168.2.92
      http:
        port: 80
    
    serviceDns:
      type: LoadBalancer
      loadBalancerIP: 192.168.2.92
    
    serviceDhcp:
      enabled: false
    
    ftl:
      FTLCONF_LOCAL_IPV4: 192.168.2.92
