- name: Install Longhorn Dependencies
  ansible.builtin.apt:
    pkg:
    - open-iscsi
    - nfs-common
    - cryptsetup
    - dmsetup
    update_cache: true
    cache_valid_time: 3600

- name: Ensure dm_crypt module is loaded
  community.general.modprobe:
    name: dm_crypt
    state: present
    persistent: present

- name: Ensure iscsi_tcp module is loaded
  community.general.modprobe:
    name: iscsi_tcp
    state: present
    persistent: present

- name: Ensure iscsi daemon is running
  ansible.builtin.systemd_service:
    state: started
    name: iscsid

- name: Copy Longhorn Manifest
  ansible.builtin.template:
    src: "longhorn.yaml"
    dest: "/var/lib/rancher/k3s/server/manifests/longhorn.yaml"
    mode: "0600"